# Generated by Django 5.0.1 on 2024-03-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("primary", "0005_alter_doctor_id_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domicilio", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("numero_ficha", models.CharField(max_length=10)),
                ("tipo_sangre", models.CharField(max_length=10)),
                (
                    "id_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="primary.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="doctor_paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="primary.doctor"
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secondary.paciente",
                    ),
                ),
            ],
        ),
    ]
