# Generated by Django 5.0.1 on 2024-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_const_vitales'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ant_familiar',
            field=models.CharField(default='Ninguno', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ant_personal',
            field=models.CharField(default='Ninguno', max_length=100),
        ),
    ]
