# Generated by Django 5.0.1 on 2024-03-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_paciente_ant_familiar_paciente_ant_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='const_vitales',
            old_name='frec_cardiaca',
            new_name='frec_respiratoria',
        ),
        migrations.AddField(
            model_name='const_vitales',
            name='talla',
            field=models.FloatField(null=True),
        ),
    ]
