# Generated by Django 5.0.1 on 2024-02-12 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rec_senecyt", models.CharField(max_length=10)),
                ("especialidad", models.CharField(max_length=100)),
                ("institucion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domicilio", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateTimeField()),
                ("numero_ficha", models.CharField(max_length=10)),
                ("tipo_sangre", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=10)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("correo", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=10)),
                ("sexo", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="doctor_paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="primary.doctor"
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="primary.paciente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paciente",
            name="id_persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="primary.persona"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="id_persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="primary.persona"
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="primary.usuario"
            ),
        ),
    ]
