# Generated by Django 5.0.1 on 2024-02-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("primary", "0002_alter_persona_id_usuario_delete_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="rec_senecyt",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="fecha_nacimiento",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="persona",
            name="correo",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
