# Generated by Django 5.0.1 on 2024-03-12 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("primary", "0003_alter_doctor_rec_senecyt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="id_persona",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="id_usuario",
        ),
        migrations.AddField(
            model_name="doctor",
            name="id_usuario",
            field=models.ForeignKey(
                default=21,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="doctor_paciente",
        ),
        migrations.DeleteModel(
            name="paciente",
        ),
    ]
