# Generated by Django 5.0.1 on 2024-03-12 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertiary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_personas', to='tertiary.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_personas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DoctorPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tertiary.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalle', models.TextField()),
                ('id_doctor_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tertiary.doctorpaciente')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_ficha', models.CharField(max_length=50)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tertiary.persona')),
            ],
        ),
        migrations.AddField(
            model_name='doctorpaciente',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tertiary.paciente'),
        ),
    ]
