# Generated by Django 5.0.1 on 2024-03-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tertiary", "0002_alter_doctor_id_persona_alter_persona_id_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="id_persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tertiary.persona"
            ),
        ),
    ]
