# Generated by Django 5.0.1 on 2024-03-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
        ('tertiary', '0003_alter_doctor_id_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpaciente',
            name='id_doctor',
        ),
        migrations.RemoveField(
            model_name='doctorpaciente',
            name='id_paciente',
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_doctor_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary.doctor_paciente'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='DoctorPaciente',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
