# Generated by Django 5.0.1 on 2024-03-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertiary', '0004_remove_doctorpaciente_id_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='detalle',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
